### ISSUE TITLE
Broader tab list to reduce confliction

### ISSUE THREAD

**Issue by ItsPasi** [MicrocontrollersDev/TabTweaks#2]
Other mods like "Better Ping Display" make the tab list wider to make more space for the ping display and reduce overlapping. This might be a good option for this mod as well. 

Vanilla:
![Vanilla](https://github.com/user-attachments/assets/ba6f32ca-e537-4a4c-b31a-7a9dbcaf1295)
Better Ping Display:
![Better Ping Display](https://github.com/user-attachments/assets/81b55d40-d89a-4f30-b66f-ee3659ca9444)
Tab Tweaks:
![Tab Tweaks](https://github.com/user-attachments/assets/3cec7910-143a-4920-9f34-362873f4f1f6)

**Comment by MicrocontrollersDev** [comment]
completed as of https://github.com/MicrocontrollersDev/TabTweaks/commit/43314c1420c3eeb2276949aa42940576e0b30c9a and https://modrinth.com/mod/tabtweaks/version/1.3.3
